-- This file has been generated by Dungeon Editor 2.1.18

-- import standard assets
import "assets/scripts/standard_assets.lua"

-- import custom assets
--import "mod_assets/scripts/items.lua"
import "mod_assets/scripts/monsters.lua"
import "mod_assets/scripts/objects.lua"
import "mod_assets/scripts/tiles.lua"
import "mod_assets/scripts/recipes.lua"
import "mod_assets/scripts/spells.lua"
import "mod_assets/scripts/materials.lua"
import "mod_assets/scripts/sounds.lua"

-- Cameron Callahan's SocketSystem
import "mod_assets/scripts/socketSystem/socketItems.lua"

defineObject{
   name = "party",
   baseObject = "party",
   components = {
      {
        class = "Party",  
		onPickUpItem = function(self, item)
		-- General Triggers Below (Skill/Trait triggers, etc)
			if item.go.item:hasTrait("shield") and not item.go:getComponent("sockets") then
				item.go:createComponent("Counter", "sockets")
				item.go.sockets:setValue(1)
				item.go:createComponent("Counter", "gemcount")
				item.go.gemcount:setValue(1)
				item.go.item:setGameEffect("1 free socket.")
			elseif item.go.item:hasTrait("chest_armor") and not item.go:getComponent("sockets") then
				item.go:createComponent("Counter", "sockets")
				item.go.sockets:setValue(2)
				item.go:createComponent("Counter", "gemcount")
				item.go.gemcount:setValue(2)
				item.go.item:setGameEffect("2 free sockets.")
			elseif (item.go:getComponent("meleeattack") or item.go:getComponent("rangedattack") or item.go:getComponent("firearmattack")) then
				if item.go.item:hasTrait("two_handed") then
					item.go:createComponent("Counter", "sockets")
					item.go.sockets:setValue(2)
					item.go:createComponent("Counter", "gemcount")
					item.go.gemcount:setValue(2)
					item.go.item:setGameEffect("2 free sockets.")
				else
					item.go:createComponent("Counter", "sockets")
					item.go.sockets:setValue(1)
					item.go:createComponent("Counter", "gemcount")
					item.go.gemcount:setValue(1)
					item.go.item:setGameEffect("1 free socket.")
				end
			end
			return
		end,
		},
   },
}

